import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import * as fs from 'fs/promises';
import * as path from 'path';
import { randomUUID } from 'crypto';
import { exec } from 'node:child_process';
import { promisify } from 'node:util';
import { getDataFilePath } from '../common/paths';

const execAsync = promisify(exec);

export interface MailingList {
  id: string;
  domain: string;
  name: string; // The address name e.g. "team" for "team@domain.com"
  subscribers: string[];
  createdAt: string;
  updatedAt: string;
}

@Injectable()
export class MailingListsService {
  private readonly logger = new Logger(MailingListsService.name);

  private get dataPath() {
    return getDataFilePath('mailing-lists.json');
  }

  private async readAll(): Promise<MailingList[]> {
    try {
      const raw = await fs.readFile(this.dataPath, 'utf-8');
      return JSON.parse(raw);
    } catch {
      return [];
    }
  }

  private async writeAll(data: MailingList[]) {
    await fs.mkdir(path.dirname(this.dataPath), { recursive: true });
    await fs.writeFile(this.dataPath, JSON.stringify(data, null, 2));
  }

  async list(domain: string): Promise<MailingList[]> {
    const all = await this.readAll();
    return all.filter(l => l.domain === domain);
  }

  async create(data: { domain: string; name: string; subscribers: string[] }): Promise<{ success: boolean; list: MailingList }> {
    const all = await this.readAll();
    const address = `${data.name}@${data.domain}`.toLowerCase();
    
    // basic sanity checks
    if (!data.name || !data.domain || !data.name.match(/^[a-zA-Z0-9.\-_]+$/)) {
      throw new BadRequestException('Invalid mailing list name');
    }

    if (all.some(l => `${l.name}@${l.domain}`.toLowerCase() === address)) {
      throw new BadRequestException(`Mailing list ${address} already exists`);
    }

    const cleanedSubscribers = (data.subscribers || [])
      .map(s => s.trim().toLowerCase())
      .filter(s => s.includes('@')); // basic valid email filter

    const list: MailingList = {
      id: randomUUID(),
      domain: data.domain,
      name: data.name,
      subscribers: [...new Set(cleanedSubscribers)],
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };

    all.push(list);
    await this.writeAll(all);
    await this.syncVirtualAliases();

    return { success: true, list };
  }

  async deleteList(id: string) {
    const all = await this.readAll();
    const idx = all.findIndex(l => l.id === id);
    if (idx === -1) throw new BadRequestException('Mailing list not found');

    all.splice(idx, 1);
    await this.writeAll(all);
    await this.syncVirtualAliases();
    return { success: true };
  }

  async addSubscriber(id: string, email: string) {
    const all = await this.readAll();
    const list = all.find(l => l.id === id);
    if (!list) throw new BadRequestException('Mailing list not found');

    const cleanEmail = email.trim().toLowerCase();
    if (!cleanEmail.includes('@')) throw new BadRequestException('Invalid email address');

    if (!list.subscribers.includes(cleanEmail)) {
      list.subscribers.push(cleanEmail);
      list.updatedAt = new Date().toISOString();
      await this.writeAll(all);
      await this.syncVirtualAliases();
    }
    return { success: true, list };
  }

  async removeSubscriber(id: string, email: string) {
    const all = await this.readAll();
    const list = all.find(l => l.id === id);
    if (!list) throw new BadRequestException('Mailing list not found');

    const cleanEmail = email.trim().toLowerCase();
    list.subscribers = list.subscribers.filter(s => s !== cleanEmail);
    list.updatedAt = new Date().toISOString();
    
    await this.writeAll(all);
    await this.syncVirtualAliases();
    
    return { success: true, list };
  }

  /**
   * Translates the JSON state into Postfix virtual aliases for mailing lists.
   * postfix/virtual_aliases allows multiple comma-separated destinations.
   * We will write the lists to /etc/postfix/virtual_lists to keep it isolated from primary aliases.
   */
  private async syncVirtualAliases() {
    try {
      const isProd = process.env.NODE_ENV === 'production';
      const mapPath = isProd ? '/etc/postfix/virtual_lists' : path.join(process.cwd(), '..', 'backend', 'mail-state', 'virtual_lists');
      
      const all = await this.readAll();
      const lines = [
        '# Auto-generated by clearPanel MailingListsService',
        '# Do not edit manually',
        ''
      ];

      for (const list of all) {
        if (list.subscribers.length > 0) {
          const source = `${list.name}@${list.domain}`;
          const destinations = list.subscribers.join(', ');
          lines.push(`${source}   ${destinations}`);
        }
      }

      await fs.mkdir(path.dirname(mapPath), { recursive: true });
      await fs.writeFile(mapPath, lines.join('\n') + '\n', 'utf-8');

      if (isProd) {
        // Ensure main.cf has virtual_alias_maps including hash:/etc/postfix/virtual_lists.
        // We will assume that installing clearpanel handles the main.cf part.
        // For here, just run postmap:
        await execAsync(`postmap ${mapPath}`);
        await execAsync(`postfix reload`);
      }
    } catch (e: any) {
      this.logger.error(`Failed to sync virtual aliases for mailing lists: ${e.message}`);
    }
  }
}
